FROM python:3.7.3

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install numpy && \
    pip install pandas && \
    pip install requests && \
    pip install BeautifulSoup4 && \
    pip install lxml && \
    pip install pymongo && \
    pip install PyYAML

WORKDIR /app